### ISSUE TITLE
Implement "Rule Actions"

### ISSUE THREAD

**Issue by jdkato** [errata-ai/vale-server#3]
This has been discussed a number of times over at the Vale repo, but I think Vale Server offers a much better opportunity to implement this well. The goal is fairly simple: allow rule definitions to provide "fixes" that can activated in our various client applications&mdash;e.g., VS Code's 'Quick Fix' interface:

<img width="834" alt="Screen Shot 2019-07-15 at 7 05 14 PM" src="https://user-images.githubusercontent.com/8785025/61260535-7e8f4500-a733-11e9-8686-1484722902d7.png">

## Target extensions

My initial targets for including this feature are: `existence`, `substitution`, `repetition`, `consistency`, and `capitalization`.

## Implementations

WIP.

**Comment by ChrisChinchilla** [comment]
I did make some very initial investigations into this, but you are generally a far quicker coder than me ;)

While we're on this topic, I was also thinking of somehow also maybe providing better guidance on rules. There is the one line at the moment, but maybe also a link, or something like that explaining _why_ you should follow this advice. Maybe that could be handled by just better written descriptions.

**Comment by jdkato** [comment]
There is a `description` key available currently (I'm not sure if that's what you were referring to) for all the extension points. Here's an example:

```yaml
extends: existence
link: 'https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/f/fail'
ignorecase: true
level: suggestion
# Ideally this should fit on a single line.
message: "Only use '%s' to refer to disks and other hardware."
# Expanded reasoning can be provided here.
description: |
  Use 'stop' responding to refer to programs or the operating
  system.

  It's OK to use fail in content for a technical audience to describe an error
  condition. For example, E_FAIL is a common return value in COM programs. A
  function that returns E_FAIL has failed to do something.
tokens:
  - 'fail(?:ed)?'
```

Admittedly, though, I haven't been very good at actually using it.
