### ISSUE TITLE
When using context on vale server, action parameter from vale is not populated

### ISSUE THREAD

**Issue by spacedsweden** [errata-ai/vale-server#77]
I am trying to get Quickfix to work for replace rule 

```
extends: substitution
message: "Consider using '%s' instead of '%s'."
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-simple-words-concise-sentences
ignorecase: true
level: suggestion
action:
  name: replace
swap:
 modify: change
```

Extension setting (doesnt really matter its api thing this i believe

Using the VS code plugin  the plugin calls /vale 
```
text: You can modify an ongoing call using [SVAML](svaml.mdx) actions and instructions.
format: .mdx 

```
response from vale endpoint
{
    "C:\\Users\\chris\\AppData\\Local\\Temp\\FxiDyX.mdx": [
        {
            "Action": {
                "Name": "replace",
                "Params": null
            },
            "Check": "Sinch.ComplexWords",
            "Description": "",
            "Line": 1,
            "Link": "https://docs.microsoft.com/en-us/style-guide/word-choice/use-simple-words-concise-sentences",
            "Message": "Consider using 'change' instead of 'modify'.",
            "Severity": "suggestion",
            "Span": [
                9,
                14
            ],
            "Match": "modify"
        }
    ]
}

expected response 

{
    "C:\\Users\\chris\\AppData\\Local\\Temp\\FxiDyX.mdx": [
        {
            "Action": {
                "Name": "replace",
                "Params": 
                      - change
            },
            "Check": "Sinch.ComplexWords",
            "Description": "",
            "Line": 1,
            "Link": "https://docs.microsoft.com/en-us/style-guide/word-choice/use-simple-words-concise-sentences",
            "Message": "Consider using 'change' instead of 'modify'.",
            "Severity": "suggestion",
            "Span": [
                9,
                14
            ],
            "Match": "modify"
        }
    ]
}

So when /suggest is called, there is of course no quickfixes .
